//Delete an user
DELETE http://localhost:3002/api/users/618d14cc481c205a4a8ca876 
token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOGQxNGNjNDgxYzIwNWE0YThjYTg3NiIsImlhdCI6MTYzNzE3MDIwOSwiZXhwIjoxNjM3Nzc1MDA5fQ.Ir_gQl9nwOO5GcBCCYY9I_t4YMZyC2igj4vLa_Njgys 
